version: "3.8"

services:
  app:
    build:
      context: .
      args:
        NODE_ENV: ${NODE_ENV}
    container_name: secufi_app
    restart: unless-stopped
    environment:
      NODE_ENV: ${NODE_ENV}
      DATABASE_URL: ${DATABASE_URL}
      PORT: ${PORT}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      GOOGLE_REDIRECT_URI: ${GOOGLE_REDIRECT_URI}
      JWT_SECRET: ${JWT_SECRET}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}
      JWT_EXPIRY: ${JWT_EXPIRY:-10d}
      JWT_REFRESH_EXPIRY: ${JWT_REFRESH_EXPIRY:-70d}
      JWT_ISSUER: ${JWT_ISSUER:-my-app}
      JWT_AUDIENCE: ${JWT_AUDIENCE:-my-app-users}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_REGION: ${AWS_REGION}
      AWS_S3_BUCKET_NAME: ${AWS_S3_BUCKET_NAME}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_BEARER_TOKEN_BEDROCK: ${AWS_BEARER_TOKEN_BEDROCK}
      ENCRYPTION_KEY: ${ENCRYPTION_KEY}
      SMTP_HOST: smtp.gmail.com
      SMTP_PORT: 587
      SMTP_USER: secufi.test@gmail.com
      SMTP_PASS: ${SMTP_PASS}
      SENDER_NAME: "Secufi Inc"
      SENDER_EMAIL: secufi.test@gmail.com
      SERVER_KEY: ${SERVER_KEY}
    env_file:
      - .env
    volumes:
      - ./uploads:/app/uploads
      - ./tmp:/app/tmp

volumes:
  postgres_dev_data:
  postgres_prod_data:

networks:
  secufi_dev_network:
    driver: bridge
  secufi_prod_network:
    driver: bridge
